config/routes.rb
Moviemania20::Application.routes.draw do

  get '/auth/:provider/callback',			:to => 'sessions#create'
  get '/auth/failure',									:to => redirect('/')
  get 'signout', :to => 'sessions#destroy', :as => 'signout'

  resources :enquiries
  resources :cinemas do
  	resources :nowshowings do
  		resources :comments
  		resources :reservations
  	end
  	resources :comingsoons do
  		resources :forumcomingsoons
  	end
  end

  devise_for :admins
  root 'pages#home'
  get "/contacts",							:to => "pages#contacts"
  get "/about",									:to => "pages#about"
  get "/help",									:to => "pages#help"
  get "/partners",							:to => "pages#partners"
  get "/allnowshowing",					:to => "pages#allnowshowing"
  get "/allcomingsoon",					:to => "pages#allcomingsoon"
  get "/allreservations",				:to => "pages#allreservations"

end

app/models/nowshowing.rb
# == Schema Information
#
# Table name: nowshowings
#
#  id              :integer          not null, primary key
#  title           :string(255)
#  synopsis        :text
#  youtubestub     :string(255)
#  price           :decimal(, )
#  created_at      :datetime
#  updated_at      :datetime
#  category        :string(255)
#  nowshowingcover :string(255)
#  cinema_id       :integer
#  screening_time  :time
#

class Nowshowing < ActiveRecord::Base
	belongs_to :cinema
	has_many :comments, :dependent => :destroy
	has_many :reservations,:dependent => :destroy
	default_scope :order => "nowshowings.created_at DESC"

	searchable do
		text :title
	end

	mount_uploader :nowshowingcover, NowshowingcoverUploader

	validates :title,	presence: true,
						length: {maximum: 50}
	validates :synopsis,	presence: true
	validates :youtubestub,	presence: true
	validates :price,	presence: true
	#validates :cinemashowing,	presence: true
	validates :category,	presence: true
	validates :nowshowingcover,	presence: true
	validates :cinema_id, :presence => true
	validates :screening_time, :presence => true

end

app/controllers/nowshowing_controller.rb
class NowshowingController < ApplicationController
  def index
  	@nowshowing = Nowshowing.all
  	@title = "Now Showing"
  end

  def new
  	@nowshowing = Nowshowing.new
  	@title = "New Now Showing"
  end

  def edit
  	@nowshowing = Nowshowing.find(params[:id])
  	@title = "Edit Now Showing"
  end

  def show
  	@nowshowing = Nowshowing.find(params[:id])
  	@title = @nowshing.title
  end

  def update
  	@title = "Update Now Showing"
  	@nowshowing = Nowshowing.find(params[:id])
  end

  def create
  	@nowshowing = Nowshowing.new(params.require(:nowshowing).permit(:title, :synopsis, :youtubestub, :price, :category, :cinemashowing, :nowshowingcover))

  	if @nowshowing.save
			redirect_to nowshowing_index_path, :notice => "The movie was successfully saved."
		else
			render "new"
		end
  end

  def destroy
  	@nowshowing = Nowshowing.find(params[:id])
		@nowshing.destroy
		redirect_to nowshowing_index_path, :notice => "The movie has been successfully deleted."
  end
end

app/controllers/nowshowings_controller.rb
class NowshowingsController < ApplicationController

	before_action :load_cinema
	before_action :set_nowshowing, only: [:show, :edit, :update, :destroy]

  def index
  	@nowshowings = @cinema.nowshowings
  	@title = "Now Showing"
  end

  def new
  	@nowshowing = @cinema.nowshowings.build
  	@title = "New Now Showing"
  end

  def edit
  	@title = "Edit #{@nowshowing.title}"
  end

  def show
  	@title = @nowshowing.title
  end

  def update
  	@title = "Update #{@nowshowing.title}"

  	if @nowshowing.update_attributes(nowshowing_params)
			redirect_to cinema_nowshowings_path, :notice => "The movie details have been successfully updated"
		else
			render "edit"
		end
  end

  def create
  	@nowshowing = @cinema.nowshowings.build(nowshowing_params)

  	if @nowshowing.save
			redirect_to cinema_nowshowings_path, :notice => "The movie was successfully saved."
		else
			render "new"
		end
  end

  def destroy
		@nowshowing.destroy
		redirect_to cinema_nowshowings_path, :notice => "The movie has been successfully deleted."
  end

  private

  def load_cinema
  	@cinema = Cinema.find(params[:cinema_id])
  end

  def set_nowshowing
  	@nowshowing = @cinema.nowshowings.find(params[:id])
  end

  def nowshowing_params
  	params.require(:nowshowing).permit(:title, :synopsis, :youtubestub, :price, :category, :nowshowingcover, :screening_time)
  end
end

app/helpers/nowshowing_helper.rb
module NowshowingHelper
end

app/helpers/nowshowings_helper.rb
module NowshowingsHelper
end

app/views/nowshowings/create.html.erb
<h1>Nowshowing#create</h1>
<p>Find me in app/views/nowshowing/create.html.erb</p>

app/views/nowshowings/destroy.html.erb
<h1>Nowshowing#destroy</h1>
<p>Find me in app/views/nowshowing/destroy.html.erb</p>

app/views/nowshowings/edit.html.erb
<%= form_for ([@cinema, @nowshowing]), :html => {:multipart => true} do |f|%>

	<div class="row">
		<div class="center">
			<fieldset class="round">
				<legend>Edit Movie Post</legend>

				<%= f.label :title %><br />
				<%= f.text_field :title%><br />

				<%= f.label :synopsis %><br />
				<%= f.text_area :synopsis%><br />

				<%= f.label :category %> <br />
				<%= f.select :category, options_for_select(%w[Animation Comedy Drama Fantasy Horror Sci-fi Thriller]) %>

				<%= f.label :youtube_stub %><br />
				<%= f.text_field :youtubestub%><br />

				<%= f.label :price %><br />
				<%= f.text_field :price %><br />

				<%= f.hidden_field :cinema_id %>

				<div class="row">
					<fieldset class="panel">
						<legend><%= f.label :screening_time %></legend>

						<div class="large-3 columns">
							<%= f.time_select :screening_time,
								:combined => true,
								:default => Time.now.change(:hour => 11, :min => 30),
								:minute_interval => 15,
								:time_separator =>" ",
								:start_hour => 6,
								:start_minute => 30,
								:end_hour => 23,
								:end_minute => 30
							%>
						</div>

					</fieldset>

				</div>

				<%= image_tag @nowshowing.nowshowingcover.url(:thumb) %>

				<%= f.label :nowshowingcover %>
				<%= f.file_field :nowshowingcover %>

				<%= f.label :remote_nowshowingcover_url, " or image URL" %>
				<%= f.text_field :remote_nowshowingcover_url %> <br />

				<%= f.submit "Submit", :class => "small button radius" %>

			</fieldset>
		</div>
	</div>

<% end %>

app/views/nowshowings/index.html.erb
<div class="row">
	<% @cinema.nowshowings.each do |nowshowing| %>

	<div class="large-4 columns">
		<%= link_to (image_tag nowshowing.nowshowingcover.url(:thumb), :class => "round center"), cinema_nowshowing_path(@cinema, nowshowing)%>
		<h5><%= nowshowing.title %></h5>
		<p><%= nowshowing.category %></p>
		<p>Price : <%= number_to_currency nowshowing.price %></p>
		<p><%= nowshowing.synopsis %></p>
		<p>
			<%= link_to "Show", cinema_nowshowing_path(@cinema, nowshowing)%> |
			<%= link_to "Watch Trailer", cinema_nowshowing_path(@cinema, nowshowing) %> |
			<% if admin_signed_in? %>
				<%= link_to "Edit", edit_cinema_nowshowing_path(@cinema, nowshowing) %> |
				<%= link_to "Destroy", [@cinema, nowshowing], :confirm => "Are you sure you want to delete this movie?", :method => :delete %>

			<% end %>
		</p>
	</div>

	<% end %>
</div>

app/views/nowshowings/new.html.erb
<div class="row">
	<div class="large-12 columns">
		<p><%= link_to "Back", cinemas_path %><p>
	</div>
</div>


<%= form_for ([@cinema, @nowshowing]), :html => {:multipart => true} do |f|%>
<%= render 'shared/nowshowing_error_messages' %>
	<div class="row">
		<div class="center">
			<fieldset class="round">
				<legend>New Movie Post</legend>

				<%= f.label :title %> <br />
				<%= f.text_field :title %>

				<%= f.label :synopsis %> <br />
				<%= f.text_area :synopsis %>

				<%= f.label :category %> <br />
				<%= f.select :category, options_for_select(%w[Animation Comedy Drama Fantasy Horror Sci-fi Thriller]) %>

				<%= f.label :youtube_stub %>
				<%= f.text_field :youtubestub %>

				<%= f.label :price %>
				<%= f.text_field :price %>

				<%= f.hidden_field :cinema_id %>

				<div class="row">
					<fieldset class="panel">
						<legend><%= f.label :screening_time %></legend>

						<div class="large-3 columns">
							<%= f.time_select :screening_time,
								:combined => true,
								:default => Time.now.change(:hour => 11, :min => 30),
								:minute_interval => 15,
								:time_separator =>" ",
								:start_hour => 6,
								:start_minute => 30,
								:end_hour => 23,
								:end_minute => 30
							%>
						</div>

					</fieldset>

				</div>

				<%= f.label :nowshowingcover %> <br />
				<%= f.file_field:nowshowingcover %>

				<%= f.label :remote_nowshowingcover_url, " or image URL" %>
				<%= f.text_field :remote_nowshowingcover_url %> <br />

				<%= f.submit "Submit", :class => "small button radius" %>
			</fieldset>
			</div>
		</div>

<% end %>

<div class="row">
	<div class="large-12 columns">
		<p><%= link_to "Back", cinemas_path %><p>
	</div>
</div>

app/views/nowshowings/show.html.erb
<div class="row">
	<div class="large-12 columns">
		<p><%= link_to "Back", cinema_nowshowings_path(@cinema) %><p>
	</div>
</div>

<div class="row">
	<div class="large-12 columns">
			<%= image_tag @nowshowing.nowshowingcover.url(:large), :class => "round center" %> <br />
			<h5>Title : <%= @nowshowing.title %></h5>
			<p>Category : <%= @nowshowing.category %></p>
			<p><%= @nowshowing.synopsis %></p>
			<p>Price : <%= number_to_currency @nowshowing.price %></p>
			<p>Time Showing : <%= @nowshowing.screening_time %></p>

			<div class="reservationbutton">
				<a class="small radius button" href=<%= new_cinema_nowshowing_reservation_path(@cinema, @nowshowing) %>>Reserve a seat</a>
			</div>
	</div>

</div>

<div class="row">
	<div class="twelve columns">
		<h4 style="text-align:center">Trailer</h4>

		<!--The video player iframe goes here-->
<iframe id="player" class="center" type="text/html" width="640" height="390"
  src="http://www.youtube.com/embed/<%= @nowshowing.youtubestub%>?enablejsapi=1&origin=http://example.com"
  frameborder="0"></iframe>

	<script>
		 //This code loads the IFrame Player API code asynchronously.
      var tag = document.createElement('script');

      tag.src = "https://www.youtube.com/iframe_api";
      var firstScriptTag = document.getElementsByTagName('script')[0];
      firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

      //This function creates an <iframe> (and YouTube player)
      //after the API code downloads.
      var player;
      function onYouTubeIframeAPIReady() {
        player = new YT.Player('player', {
          events: {
            'onReady': onPlayerReady,
            'onStateChange': onPlayerStateChange
          }
        });
      }

      //The API will call this function when the video player is ready.
      function onPlayerReady(event) {
        event.target.playVideo();
      }

      //The API calls this function when the player's state changes.
      //The function indicates that when playing a video (state=1),
      //the player should play for six seconds and then stop.
      var done = false;
      function onPlayerStateChange(event) {
        if (event.data == YT.PlayerState.PLAYING && !done) {
          setTimeout(stopVideo, 6000);
          done = true;
        }
      }
      function stopVideo() {
        player.stopVideo();
      }
	</script>

	</div>
</div>

<div class="row">
	<div class="large-12 columns">
		<p><%= link_to "Back", cinema_nowshowings_path(@cinema) %><p>
	</div>
</div>

<!--Comments and Reviews-->
<div class="commentswrapper round">
	<div class="comments">
		<h4 style="text-align:center">Forum</h4>
		<%= render :partial => @nowshowing.comments%>

		<% if current_user %>

			<%= form_for [@cinema, @nowshowing, Comment.new] do |f| %>
				<p>
					<%= f.text_area :body, :label => "New comment/review", as: :text, input_html: {rows:"3"}, :class => "round" %>
				</p>
				<%= f.submit "Post", :class => "small radius button" %>
			<% end %>

		<% else %>

			<h4 style="text-align:center;">Sign up through one of these services to participate in the forum</h4>
			<%= link_to image_tag("twitter.png", :alt => 'twitter', :class => "round", :width => 64, :height => 64), "/auth/twitter", :id => "sign_in" %>
			<%= link_to image_tag("facebook.png", :alt => 'facebook', :class => "round", :width => 64, :height => 64), "/auth/facebook", :id => "sign_in" %>

		<% end %>


	</div>
</div>

app/views/nowshowings/update.html.erb
<h1>Nowshowing#update</h1>
<p>Find me in app/views/nowshowing/update.html.erb</p>