config/routes.rb
Moviemania20::Application.routes.draw do

  get '/auth/:provider/callback',			:to => 'sessions#create'
  get '/auth/failure',									:to => redirect('/')
  get 'signout', :to => 'sessions#destroy', :as => 'signout'

  resources :enquiries
  resources :cinemas do
  	resources :nowshowings do
  		resources :comments
  		resources :reservations
  	end
  	resources :comingsoons do
  		resources :forumcomingsoons
  	end
  end

  devise_for :admins
  root 'pages#home'
  get "/contacts",							:to => "pages#contacts"
  get "/about",									:to => "pages#about"
  get "/help",									:to => "pages#help"
  get "/partners",							:to => "pages#partners"
  get "/allnowshowing",					:to => "pages#allnowshowing"
  get "/allcomingsoon",					:to => "pages#allcomingsoon"
  get "/allreservations",				:to => "pages#allreservations"

end

app/models/comingsoon.rb
# == Schema Information
#
# Table name: comingsoons
#
#  id              :integer          not null, primary key
#  title           :string(255)
#  synopsis        :text
#  category        :string(255)
#  youtubestub     :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#  comingsooncover :string(255)
#  cinema_id       :integer
#  release_date    :string(255)
#

class Comingsoon < ActiveRecord::Base

	belongs_to :cinema
	has_many :forumcomingsoons, :dependent => :destroy
	default_scope :order => "comingsoons.created_at DESC"

	mount_uploader :comingsooncover, ComingsooncoverUploader

	validates :title,	presence: true,
						length: {maximum: 50}
	validates :synopsis,	presence: true
	validates :category,	presence: true
	validates :youtubestub,	presence: true
	validates :comingsooncover,	presence: true
	validates :cinema_id, :presence => true
	validates :release_date, :presence => true

end

app/controllers/comingsoons_controller.rb
class ComingsoonsController < ApplicationController

  before_action :load_cinema
	before_action :set_comingsoon, only: [:show, :edit, :update, :destroy]

  def index
  	@title = "Coming Soon"
  	@comingsoons = @cinema.comingsoons
  end

  def new
  	@title = "New Movie"
  	@comingsoon = @cinema.comingsoons.build
  end

  def show
  	@title = @comingsoon.title
  end

  def edit
  	@title = "Edit #{@comingsoon.title}"
  end

  def update
  	@title = "Update #{@comingsoon.title}"

  	if @comingsoon.update_attributes(comingsoon_params)
			redirect_to cinema_comingsoons_path, :notice => "The movie details have been successfully updated"
		else
			render "edit"
		end
  end

  def create
  	@comingsoon = @cinema.comingsoons.build(comingsoon_params)

  	if @comingsoon.save
			redirect_to cinema_comingsoons_path, :notice => "The movie was successfully saved"
		else
			render "new"
		end
  end

  def destroy
		@comingsoon.destroy
		redirect_to comingsoons_path, :notice => "The movie has been deleted."
  end

  private

  def load_cinema
  	@cinema = Cinema.find(params[:cinema_id])
  end

  def set_comingsoon
  	@comingsoon = @cinema.comingsoons.find(params[:id])
  end

  def comingsoon_params
		params.require(:comingsoon).permit(:title, :synopsis, :youtubestub, :category, :comingsooncover, :release_date)
  end
end

app/helpers/comingsoons_helper.rb
module ComingsoonsHelper
end

app/views/comingsoons/create.html.erb
<h1>Comingsoons#create</h1>
<p>Find me in app/views/comingsoons/create.html.erb</p>

app/views/comingsoons/destroy.html.erb
<h1>Comingsoons#destroy</h1>
<p>Find me in app/views/comingsoons/destroy.html.erb</p>

app/views/comingsoons/edit.html.erb
<div class="row">
	<div class="large-12 columns">
		<p><%= link_to "Back", cinema_nowshowings_path(@cinema) %><p>
	</div>
</div>

<%= form_for ([@cinema, @comingsoon]), :html => {:multipart => true} do |f|%>

	<div class="row">
		<div class="center">
			<fieldset class="round">
				<legend>Edit Movie Post</legend>

				<%= f.label :title %><br />
				<%= f.text_field :title%><br />

				<%= f.label :synopsis %><br />
				<%= f.text_area :synopsis%><br />

				<%= f.label :category %> <br />
				<%= f.select :category, options_for_select(%w[Animation Comedy Drama Fantasy Horror Sci-fi Thriller]) %>

				<%= f.label :youtube_stub %><br />
				<%= f.text_field :youtubestub%><br />

				<%= f.hidden_field :cinema_id %>

				<%= f.label :release_date %>
				<%= f.text_field :release_date, :id => "release_date" %>

				<%= image_tag @comingsoon.comingsooncover.url(:thumb) %>

				<%= f.label :comingsooncover %>
				<%= f.file_field :comingsooncover %>

				<%= f.label :remote_comingsooncover_url, " or image URL" %>
				<%= f.text_field :remote_comingsooncover_url %> <br />

				<%= f.submit "Submit", :class => "small button radius" %>

			</fieldset>
		</div>
	</div>

<% end %>

<div class="row">
	<div class="large-12 columns">
		<p><%= link_to "Back", cinema_nowshowings_path(@cinema) %><p>
	</div>
</div>

app/views/comingsoons/index.html.erb
<div class="row">
<% @cinema.comingsoons.each do |comingsoon| %>

		<div class="large-4 columns">
				<%= link_to (image_tag comingsoon.comingsooncover.url(:large), :class => "round center"), cinema_comingsoon_path(@cinema, comingsoon) %>
				<h5><%= comingsoon.title %></h5>
				<p><%= comingsoon.category %></p>
				<p><%= comingsoon.synopsis %></p>
				<p>
					<%= link_to "Show", cinema_comingsoon_path(@cinema, comingsoon) %> |
					<%= link_to "Watch Trailer", "#" %> |

						<% if admin_signed_in? %>

						<%= link_to "Edit", edit_cinema_comingsoon_path(@cinema, comingsoon) %> |
						<%= link_to "Destroy", [@cinema, comingsoon], :confirm => "Are you sure you want to delete this movie?", :method => :delete %>
						<% end %>
					</p>
			</div>

<% end %>
</div>

app/views/comingsoons/new.html.erb
<div class="row">
	<div class="large-12 columns">
		<p><%= link_to "Back", cinemas_path %><p>
	</div>
</div>


<%= form_for ([@cinema, @comingsoon]), :html => {:multipart => true} do |f|%>
<%= render 'shared/comingsoon_error_messages' %>
	<div class="row">
		<div class="center">
			<fieldset class="round">
				<legend>New Movie Post</legend>

				<%= f.label :title %> <br />
				<%= f.text_field :title %>

				<%= f.label :synopsis %> <br />
				<%= f.text_area :synopsis %>

				<%= f.label :category %> <br />
				<%= f.select :category, options_for_select(%w[Animation Comedy Drama Fantasy Horror Sci-fi Thriller]) %>

				<%= f.label :youtube_stub %>
				<%= f.text_field :youtubestub %>

				<%= f.hidden_field :cinema_id %>

				<%= f.label :release_date %>
				<%= f.text_field :release_date, :id => "release_date" %>

				<%= f.label :comingsooncover %> <br />
				<%= f.file_field:comingsooncover %>

				<%= f.submit "Submit", :class => "small button radius" %>
			</fieldset>
			</div>
		</div>

<% end %>

<div class="row">
	<div class="large-12 columns">
		<p><%= link_to "Back", cinemas_path %><p>
	</div>
</div>

app/views/comingsoons/show.html.erb
<div class="row">
	<div class="large-12 columns">
		<p><%= link_to "Back", cinema_comingsoons_path(@cinema) %><p>
	</div>
</div>

<div class="row">
	<div class="large-12 columns">
			<%= image_tag @comingsoon.comingsooncover.url(:large), :class => "round center" %> <br />
			<h5>Title : <%= @comingsoon.title %></h5>
			<p>Category : <%= @comingsoon.category %></p>
			<p><%= @comingsoon.synopsis %></p>
			<p>Release Date : <%= @comingsoon.release_date %></p>
	</div>

</div>

<div class="row">
	<div class="twelve columns">
		<h4 style="text-align:center">Trailer</h4>

		<!--The video player iframe goes here-->
<iframe id="player" class="center" type="text/html" width="640" height="390"
  src="http://www.youtube.com/embed/<%= @comingsoon.youtubestub %>?enablejsapi=1&origin=http://example.com"
  frameborder="0"></iframe>

	<script>
		 //This code loads the IFrame Player API code asynchronously.
      var tag = document.createElement('script');

      tag.src = "https://www.youtube.com/iframe_api";
      var firstScriptTag = document.getElementsByTagName('script')[0];
      firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

      //This function creates an <iframe> (and YouTube player)
      //after the API code downloads.
      var player;
      function onYouTubeIframeAPIReady() {
        player = new YT.Player('player', {
          events: {
            'onReady': onPlayerReady,
            'onStateChange': onPlayerStateChange
          }
        });
      }

      //The API will call this function when the video player is ready.
      function onPlayerReady(event) {
        event.target.playVideo();
      }

      //The API calls this function when the player's state changes.
      //The function indicates that when playing a video (state=1),
      //the player should play for six seconds and then stop.
      var done = false;
      function onPlayerStateChange(event) {
        if (event.data == YT.PlayerState.PLAYING && !done) {
          setTimeout(stopVideo, 6000);
          done = true;
        }
      }
      function stopVideo() {
        player.stopVideo();
      }
	</script>

	</div>
</div>

<div class="row">
	<div class="large-12 columns">
		<p><%= link_to "Back", cinema_comingsoons_path(@cinema) %><p>
	</div>
</div>


<!--Comments and Reviews-->
<div class="commentswrapper round">
	<div class="comments">
		<h4 style="text-align:center">Forum</h4>
		<%= render :partial => @comingsoon.forumcomingsoons %>
		<%= form_for [@cinema, @comingsoon, Forumcomingsoon.new] do |f| %>
		<p>
			<%= f.text_area :body, :label => "New comment/review", as: :text, input_html: {rows:"3"}, :class => "round" %>
		</p>
		<%= f.submit "Post", :class => "small radius button" %>
		<% end %>
	</div>
</div>

app/views/comingsoons/update.html.erb
<h1>Comingsoons#update</h1>
<p>Find me in app/views/comingsoons/update.html.erb</p>