config/routes.rb
Moviemania20::Application.routes.draw do

  get '/auth/:provider/callback',			:to => 'sessions#create'
  get '/auth/failure',									:to => redirect('/')
  get 'signout', :to => 'sessions#destroy', :as => 'signout'

  resources :enquiries
  resources :cinemas do
  	resources :nowshowings do
  		resources :comments
  		resources :reservations
  	end
  	resources :comingsoons do
  		resources :forumcomingsoons
  	end
  end

  devise_for :admins
  root 'pages#home'
  get "/contacts",							:to => "pages#contacts"
  get "/about",									:to => "pages#about"
  get "/help",									:to => "pages#help"
  get "/partners",							:to => "pages#partners"
  get "/allnowshowing",					:to => "pages#allnowshowing"
  get "/allcomingsoon",					:to => "pages#allcomingsoon"
  get "/allreservations",				:to => "pages#allreservations"

end

app/models/cinema.rb
# == Schema Information
#
# Table name: cinemas
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  email       :string(255)
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#  cinemalogo  :string(255)
#

class Cinema < ActiveRecord::Base

	has_many :nowshowings, :dependent => :destroy
	has_many :comingsoons, :dependent => :destroy
	has_many :comments, :through => :nowshowings
	has_many :forumcomingsoons, :through => :comingsoons

	searchable do
		text :name
	end

	mount_uploader :cinemalogo, CinemalogoUploader

	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates :name,				presence: true,
													length: {maximum: 50}
	validates :email, 			presence: true,
													format: {with: email_regex},
													uniqueness: {case_sensitive: false }
	validates :description,	presence: true
	validates :cinemalogo,	presence: true

end

app/controllers/cinemas_controller.rb
class CinemasController < ApplicationController

  before_action :set_cinema, only: [:show, :edit, :update, :destroy]

  def index
		@cinemas = Cinema.all
		@title = "Cinemas"

		@search = Cinema.search do
			fulltext params[:search]
		end
		@cinemas = @search.results
  end

  def new
  	@cinema = Cinema.new
  	@title = "New Cinema"
  end

  def edit
  	@title = "Edit #{@cinema.name}"
  end

  def show
		@title = @cinema.name
  end

  def update
  	@title = "Update #{@cinema.name}"

		if @cinema.update_attributes(cinema_params)
			redirect_to cinemas_path, :notice => "The cinema details have been successfully updated"
		else
			render "edit"
		end
  end

  def create
  	@cinema = Cinema.new(cinema_params)

  	if @cinema.save
			redirect_to cinemas_path, :notice => "The cinema was successfully saved"
		else
			render "new"
		end

  end

  def destroy
		@cinema.destroy
		redirect_to cinemas_path, :notice => "The cinema has been deleted."
  end

  private

  def set_cinema
  	@cinema = Cinema.find(params[:id])
  end

  def cinema_params
  	params.require(:cinema).permit(:name, :email, :description, :cinemalogo)
  end

end

app/helpers/cinemas_helper.rb
module CinemasHelper
end

app/views/cinemas/create.html.erb
<h1>Cinemas#create</h1>
<p>Find me in app/views/cinemas/create.html.erb</p>

app/views/cinemas/destroy.html.erb
<h1>Cinemas#destroy</h1>
<p>Find me in app/views/cinemas/destroy.html.erb</p>

app/views/cinemas/edit.html.erb
<div class="row">
	<div class="large-12 columns">
		<p><%= link_to "Back", cinemas_path %><p>
	</div>
</div>


<%= form_for @cinema, :html => {:multipart => true} do |f|%>

	<div class="row">
		<div class="center">
			<fieldset class="round">
				<legend>Edit Cinema</legend>

				<%= f.label :name %><br />
				<%= f.text_field :name%><br />

				<%= f.label :email %><br />
				<%= f.text_field :email%><br />

				<%= f.label :description %><br />
				<%= f.text_field :description%><br />

				<%= image_tag @cinema.cinemalogo.url(:thumb) %>

				<%= f.file_field :cinemalogo %>

				<%= f.label :remote_cinemalogo_url, " or image URL" %>
				<%= f.text_field :remote_cinemalogo_url %> <br />

				<%= f.submit "Submit", :class => "small button radius" %>

			</fieldset>
		</div>
	</div>

<% end %>

<div class="row">
	<div class="large-12 columns">
		<p><%= link_to "Back", cinemas_path %><p>
	</div>
</div>

app/views/cinemas/index.html.erb
<div class="row">
	<div class="large-4 columns">
		<%=form_tag :cinemas, :method => :get do %>
		<%= text_field_tag :search, params[:search], :class=> "round search", :placeholder=> "Search Cinema..." %>
	<% end %>
	</div>
</div>

<% if admin_signed_in? %>
	<div class="row">
		<div class="large-4 columns">
			<a href=<%= new_cinema_path %> class="small button radius ">Add New Cinema</a>
		</div>
	</div>
<% end %>


<div class="row">

<% @cinemas.each do |cinema| %>


  		<div class="large-4 columns ">
  			<%= link_to (image_tag cinema.cinemalogo.url(:thumb), :class => "round center"), cinema %>
  			<h5><%= link_to cinema.name, cinema %></h5>
  			<p><%= cinema.description %> </p>

				<p>
						<% if admin_signed_in? %>

						<%= link_to "Add Showing", new_cinema_nowshowing_path(cinema) %> |
						<%= link_to "Add Coming Soon", new_cinema_comingsoon_path(cinema) %> |
						<%= link_to "Edit", edit_cinema_path(cinema) %> |
						<%= link_to "Destroy", cinema, :confirm => "Are you sure you want to delete this cinema?", :method => :delete %>
						<% end %></p>
  		</div>
<% end %>
</div>

app/views/cinemas/new.html.erb
<div class="row">
	<div class="large-12 columns">
		<p><%= link_to "Back", cinemas_path %><p>
	</div>
</div>


<%= form_for @cinema, :html => {:multipart => true} do |f|%>
<%= render 'shared/cinema_error_messages' %>
<div class="row">
	<div class="center">
		<fieldset class="round">
			<legend>New Cinema</legend>

			<%= f.label :name %><br />
				<%= f.text_field :name %><br />

				<%= f.label :email %>
				<%= f.text_field :email %>

				<%= f.label :description %>
				<%= f.text_area :description %>

				<%= f.file_field :cinemalogo %>

				<%= f.label :remote_cinemalogo_url, " or image URL" %>
				<%= f.text_field :remote_cinemalogo_url %> <br />

				<%= f.submit "Submit", :class => "small button radius" %>

		</fieldset>
	</div>
</div>

<% end %>

<div class="row">
	<div class="large-12 columns">
		<p><%= link_to "Back", cinemas_path %><p>
	</div>
</div>

app/views/cinemas/show.html.erb
<div class="row">
	<div class="large-12 columns">
		<p><%= link_to "Back", cinemas_path %><p>
	</div>
</div>

<div class="row">
	<div class="large-12 columns">
			<%= image_tag @cinema.cinemalogo.url(:large), :class => "round center" %> <br />
			<h5><%= link_to @cinema.name, '#' %></h5> <br />
			<p><%= @cinema.description %></p>
			<p><%= @cinema.created_at %></p>
			<p>
					<%= link_to "Now Showing", cinema_nowshowings_path(@cinema) %> |
					<%= link_to "Coming Soon", cinema_comingsoons_path(@cinema) %>
				</p>
	</div>
</div>

<div class="row">
	<div class="large-12 columns">
		<p><%= link_to "Back", cinemas_path %><p>
	</div>
</div>