config/routes.rb
Moviemania20::Application.routes.draw do

  get '/auth/:provider/callback',			:to => 'sessions#create'
  get '/auth/failure',									:to => redirect('/')
  get 'signout', :to => 'sessions#destroy', :as => 'signout'

  resources :enquiries
  resources :cinemas do
  	resources :nowshowings do
  		resources :comments
  		resources :reservations
  	end
  	resources :comingsoons do
  		resources :forumcomingsoons
  	end
  end

  devise_for :admins
  root 'pages#home'
  get "/contacts",							:to => "pages#contacts"
  get "/about",									:to => "pages#about"
  get "/help",									:to => "pages#help"
  get "/partners",							:to => "pages#partners"
  get "/allnowshowing",					:to => "pages#allnowshowing"
  get "/allcomingsoon",					:to => "pages#allcomingsoon"
  get "/allreservations",				:to => "pages#allreservations"

end

app/views/layouts/_footer.html.erb
<footer class="round">
	<div class="zurb-footer-bottom">
		<div class="row" id="navcontainer">
			<div class="small-8 columns">
				<ul>
					<li>
						<%= link_to image_tag("logo.jpg", :alt => 'logo', :class => "round", :width => 35, :height => 35), root_path %>
					</li>
					<li><%= link_to "About", about_path %></li>
					<li><%= link_to "Contacts", contacts_path %></li>
					<li><%= link_to "Contact Us", new_enquiry_path %></li>
					<li><%= link_to "Partners", partners_path %></li>
					<li><%= link_to "Help", help_path %></li>
				</ul>
				<p class="copyright">&copy;2013 EINNOR, Inc. All rights reserved.</p>

			</div>
			<div class="small-4 columns">
			<ul class="home-social">
				<li><%= link_to image_tag("twitter.png", :alt => 'twitter', :class => "round", :width => 35, :height => 35), "/auth/twitter", :id => "sign_in" %></li>
				<li><%= link_to image_tag("facebook.png", :alt => 'facebook', :class => "round", :width => 35, :height => 35), "/auth/facebook", :id => "sign_in" %>
				<li><%= link_to image_tag("mail.png", :alt => 'mail', :class => "round", :width => 35, :height => 35), new_enquiry_path %>
			</ul>
		</div>
	</div>
</div>
</footer>

app/views/layouts/_header.html.erb
<div class="logo">

</div>


<nav class="top-bar hide-for-small round">
	<ul class="title-area">
		<li class="name">
			<h4><%= link_to "MovieMania 2.0", root_path %></h4>
		</li>

		<li class="toggle-topbar"><a href="#"></a></li>
	</ul>

	<section class="top-bar-section">
		<ul class="right">
			<li class="divider"></li>
			<li><%= link_to "Home", root_path %></li>
			<li class="divider"></li>
			<li class="has-dropdown">
				<%= link_to "Cinemas", cinemas_path %>
				<% @cinemas = Cinema.all %>
				<ul class="dropdown">
				<% @cinemas.each do |cinema| %>

					<li><%= link_to cinema.name,  cinema %></li>
				<% end %>
				</ul>

			</li>
			<li class="divider"></li>
			<li class="has-dropdown">
				<%= link_to "Movies", '#' %>
				<ul class="dropdown">
					<li><%= link_to "Now Showing", allnowshowing_path %></li>
					<li><%= link_to "Coming Soon", allcomingsoon_path %></li>
				</ul>
			</li>
			<li class="divider"></li>
			<li><%= link_to "Contacts", contacts_path %></li>
			<li class="divider"></li>
			<li><%= link_to "About", about_path %></li>
			<li class="divider"></li>
			<li><%= link_to "Help", help_path%></li>
			<li class="divider"></li>

			<% if admin_signed_in? %>
				<li class="has-dropdown"><%= link_to current_admin.email, "#"%>
					<ul class="dropdown">
						<li><%= link_to "View Transactions", allreservations_path %></li>
						<li><%= link_to "View Enquiries", enquiries_path %></li>
						<li><%= link_to "Edit Profile", edit_admin_registration_path %></li>
						<li><%= link_to "Change Password", edit_admin_password_path %></li>
						<li><%= link_to "Create New Admin", new_admin_registration_path %></li>
						<li><%= link_to "Logout", destroy_admin_session_path, :method => :delete %></li>
					</ul>
				</li>
			<% else %>
				<li><%= link_to "Login", new_admin_session_path %></li>
			<% end %>

		</ul>
	</section>

</nav>

app/views/layouts/_stylesheets.html.erb
<!--Bringing Internet Explorer up to speed with HTML5-->
    <!--[if lt IE 9]>
    	<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "stylesheet/custom.css" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : title %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>

  </head>

  <body>

  	<%=  render "layouts/header"%>

  	<section role="main">
  		<div class="row">
  			<div class="twelve columns">

  				<% flash.each do |name, msg| %>
  					<% if msg.is_a?(String) %>
  						<div class="alert-box <%= name == :notice ? "success" : "alert" %>">
  							<a class="close" data-dismiss="alert">&#215;</a>
  							<%= content_tag :div, msg, :id => "flash_#{name}"%>
  						</div>
  					<% end %>
  				<% end %>

					<%= yield %>

  			</div>
  		</div>
  	</section>

  	<%= render "layouts/footer" %>


    <%= javascript_include_tag "application" %>

  </body>
</html>